java_binary(
    name = "LoggingTest",
    srcs = ["LoggingTest.java"],
    deps = [
        "@maven//:org_apache_logging_log4j_log4j_core",
        "@maven//:org_apache_logging_log4j_log4j_api",
        "@maven//:io_vavr_vavr",
    ]
)
