java_binary(
    name = "Hello",
    srcs = ["Hello.java"],
    deps = [
        "@maven//:io_vavr_vavr"
    ]
)

java_binary(
    name = "CodeGenerator",
    srcs = ["CodeGenerator.java"],
    deps = [
        "@maven//:io_swagger_codegen_v3_swagger_codegen_cli",
        "@maven//:org_yaml_snakeyaml",
    ],
)